version: "3.7"
services: 
    app:
        build: .        
        volumes: 
            - .:/app
        working_dir: /app
        ports:
            - "3000:8080"
        stdin_open: true
        tty: true
        environment: 
            - CHOKIDAR_USEPOLLING=true
        command: npm run serve